services:
  - type: web
    name: kraken-bot
    env: python
    plan: free
    branch: main
    buildCommand: ""
    startCommand: ./start.sh
    pythonVersion: 3.10.13
    envVars:
      - key: API_TOKEN
        value: 8091412559:AAHgqI_YrIiVrgIQ5jWhmMvtaV_2aSglNrg
